version: '3.8'

services:
  gateway-api:
    build:
      context: ../..
      dockerfile: docker/stg/stg-deploy.Dockerfile
    ports:
      - "10002:10002"

networks:
  default:
    external: true
    name: aimcup-network