server:
  port: 10002
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: tournament-service-route
          uri: lb://TOURNAMENT-SERVICE
          predicates:
            - Path=/tournament/**
eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.1:8762/eureka/