server:
  port: 10001
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-microservice-route
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/user/**
        - id: tournament-microservice-route
          uri: lb://TOURNAMENT-MICROSERVICE
          predicates:
            - Path=/tournament/**
eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.1:8761/eureka/