server:
  port: 9000
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: discord-service-route
          uri: lb://DISCORD-SERVICE
          predicates:
            - Path=/api/discord-service/**
        - id: tournament-service-route
          uri: lb://TOURNAMENT-SERVICE
          predicates:
            - Path=/api/tournament/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
