version: '3.8'

services:
  gateway-api:
    build:
      context: ../..
      dockerfile: docker/prd/prd-deploy.Dockerfile
    ports:
      - "10001:10001"

networks:
  default:
    external: true
    name: aimcup-network