name: Deploy to Production

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on:
      group: Default
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker-compose -f docker/prd/prd-deploy-job.yml up -d --build